// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5ngE7N9F0VTJbm2dD4MpVwHwW2fGQeDE',
    appId: '1:962165694045:web:4a820b25c56e8723d0f7b4',
    messagingSenderId: '962165694045',
    projectId: 'aastha-26950',
    authDomain: 'aastha-26950.firebaseapp.com',
    storageBucket: 'aastha-26950.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfbbeSft_xUOkh75XywjqyCKX9UNCV5tQ',
    appId: '1:962165694045:android:88c0cd4a75d7a91cd0f7b4',
    messagingSenderId: '962165694045',
    projectId: 'aastha-26950',
    storageBucket: 'aastha-26950.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXRjU8rtJnH0Hx-73wrICfTLJQypo4NRI',
    appId: '1:962165694045:ios:40c95f07293c7eded0f7b4',
    messagingSenderId: '962165694045',
    projectId: 'aastha-26950',
    storageBucket: 'aastha-26950.appspot.com',
    iosBundleId: 'com.example.newpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXRjU8rtJnH0Hx-73wrICfTLJQypo4NRI',
    appId: '1:962165694045:ios:da654727d0f895dfd0f7b4',
    messagingSenderId: '962165694045',
    projectId: 'aastha-26950',
    storageBucket: 'aastha-26950.appspot.com',
    iosBundleId: 'com.example.newpro.RunnerTests',
  );
}
